name: Deploy to Firebase Hosting (OIDC)

on:
  push:
    branches: ["main"]

permissions:
  contents: read
  id-token: write

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install
        run: npm ci

      - id: auth
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: "projects/${{ secrets.GCP_PROJECT_NUMBER }}/locations/global/workloadIdentityPools/github-pool/providers/github-provider"
          service_account: "github-firebase-deployer@${{ secrets.GCP_PROJECT_ID }}.iam.gserviceaccount.com"

      - name: Deploy to a short-lived preview channel and capture output
        run: npx firebase hosting:channel:deploy test -e 1h --project "${{ secrets.GCP_PROJECT_ID }}"

  test:
    runs-on: ubuntu-latest
    needs: setup
    strategy:
      fail-fast: false
      matrix:
        page: [creator, business, company]
    env:
      REPORTS_PATH: /tmp/lighthouse-reports
      FIREBASE_PID_FILE: /tmp/firebase-emulator.pid
      ORIGIN: https://corporate-site-d81cd--test-brpr20pn.web.app
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install
        run: npm ci

      - name: Test
        run: |
          set -euo pipefail
          REPORT_FILE="${REPORTS_PATH}/${{ matrix.page }}.json"

          mkdir -p "${REPORTS_PATH}"

          npm -s run test:lighthouse "${ORIGIN}/${{ matrix.page }}/" -- --quiet --output-path="${REPORT_FILE}" --throttling-method=provided --skip-audits="is-crawlable,robots-txt"

          npm -s run test:lighthouse-gate < "${REPORT_FILE}" | while IFS=$'\t' read -r METRIC SCORE RESULT
          do
            case "${RESULT:-}" in
            FAIL)
              echo "::error::Lighthouse gate ${METRIC} failed! (Score: ${SCORE})"
              ;;
            PASS)
              echo "::info::Lighthouse gate ${METRIC} passed. (Score: ${SCORE})"
              ;;
            *)
              ;;
            esac
          done
          exit "${PIPESTATUS[0]}"

      - name: Upload Lighthouse report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: lighthouse-reports (${{ matrix.page }})
          path: ${{ env.REPORTS_PATH }}/${{ matrix.page }}.json

  deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install
        run: npm ci

      - id: auth
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: "projects/${{ secrets.GCP_PROJECT_NUMBER }}/locations/global/workloadIdentityPools/github-pool/providers/github-provider"
          service_account: "github-firebase-deployer@${{ secrets.GCP_PROJECT_ID }}.iam.gserviceaccount.com"

      - name: Deploy to Firebase Hosting
        run: npx firebase deploy --only hosting --project "${{ secrets.GCP_PROJECT_ID }}"
